/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nofil.Khan (https://sketchfab.com/Nofil.Khan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ethereum-logo-free-3d-model-77eaebe1ae96474eb87482a9970899a9
title: Ethereum Logo | Free 3D Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/disco.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, -125.48, 13.73]} scale={100}>
            <mesh geometry={nodes.EhiriumLogo__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/disco.gltf')
